# Required metadata
sonar.projectKey=egresados_cliente
sonar.projectName=egresados_cliente
sonar.projectVersion=1.0

# Comma-separated paths to directories with sources (required)
sonar.sources=src

sonar.language=js

# Encoding of the source files
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/e2e/**,**/*.spec.ts,**/*.scss
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts

# Descomentar cuando el CI ejecute 'ng test' con cobertura
# sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Sonar Host
sonar.host.url=https://sonarqube.portaloas.udistrital.edu.co/
